version: '3'

services:
  mysqlsrv:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: "testando"
      MYSQL_DATABASE: "vinny_db"
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/Vinicius/Desktop/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
